module.exports = function () {
    var data = {
        departments:["IT", "HR", "Administration"],
        employees:[
            [
                {
                  "employeeId": 100,
                  "firstName": "Steven",
                  "lastName": "King",
                  "hireDate": "6/17/1987",
                  "email": "steven.king@sqltutorial.org",
                  "phone": "515.123.4567",
                  "salary": "$24,000.00",
                  "job": "President",
                  "department": "Executive",
                  "manager": " "
                },
                {
                  "employeeId": 101,
                  "firstName": "Neena",
                  "lastName": "Kochhar",
                  "hireDate": "9/21/1989",
                  "email": "neena.kochhar@sqltutorial.org",
                  "phone": "515.123.4568",
                  "salary": "$17,000.00",
                  "job": "Administration Vice President",
                  "department": "Executive",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 102,
                  "firstName": "Lex",
                  "lastName": "De Haan",
                  "hireDate": "1/13/1993",
                  "email": "lex.de haan@sqltutorial.org",
                  "phone": "515.123.4569",
                  "salary": "$17,000.00",
                  "job": "Administration Vice President",
                  "department": "Executive",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 103,
                  "firstName": "Alexander",
                  "lastName": "Hunold",
                  "hireDate": "1/3/1990",
                  "email": "alexander.hunold@sqltutorial.org",
                  "phone": "590.423.4567",
                  "salary": "$9,000.00",
                  "job": "Programmer",
                  "department": "IT",
                  "manager": "Lex De Haan"
                },
                {
                  "employeeId": 104,
                  "firstName": "Bruce",
                  "lastName": "Ernst",
                  "hireDate": "5/21/1991",
                  "email": "bruce.ernst@sqltutorial.org",
                  "phone": "590.423.4568",
                  "salary": "$6,000.00",
                  "job": "Programmer",
                  "department": "IT",
                  "manager": "Alexander Hunold"
                },
                {
                  "employeeId": 105,
                  "firstName": "David",
                  "lastName": "Austin",
                  "hireDate": "6/25/1997",
                  "email": "david.austin@sqltutorial.org",
                  "phone": "590.423.4569",
                  "salary": "$4,800.00",
                  "job": "Programmer",
                  "department": "IT",
                  "manager": "Alexander Hunold"
                },
                {
                  "employeeId": 106,
                  "firstName": "Valli",
                  "lastName": "Pataballa",
                  "hireDate": "2/5/1998",
                  "email": "valli.pataballa@sqltutorial.org",
                  "phone": "590.423.4560",
                  "salary": "$4,800.00",
                  "job": "Programmer",
                  "department": "IT",
                  "manager": "Alexander Hunold"
                },
                {
                  "employeeId": 107,
                  "firstName": "Diana",
                  "lastName": "Lorentz",
                  "hireDate": "2/7/1999",
                  "email": "diana.lorentz@sqltutorial.org",
                  "phone": "590.423.5567",
                  "salary": "$4,200.00",
                  "job": "Programmer",
                  "department": "IT",
                  "manager": "Alexander Hunold"
                },
                {
                  "employeeId": 108,
                  "firstName": "Nancy",
                  "lastName": "Greenberg",
                  "hireDate": "8/17/1994",
                  "email": "nancy.greenberg@sqltutorial.org",
                  "phone": "515.124.4569",
                  "salary": "$12,000.00",
                  "job": "Finance Manager",
                  "department": "Finance",
                  "manager": "Neena Kochhar"
                },
                {
                  "employeeId": 109,
                  "firstName": "Daniel",
                  "lastName": "Faviet",
                  "hireDate": "8/16/1994",
                  "email": "daniel.faviet@sqltutorial.org",
                  "phone": "515.124.4169",
                  "salary": "$9,000.00",
                  "job": "Accountant",
                  "department": "Finance",
                  "manager": "Nancy Greenberg"
                },
                {
                  "employeeId": 110,
                  "firstName": "John",
                  "lastName": "Chen",
                  "hireDate": "9/28/1997",
                  "email": "john.chen@sqltutorial.org",
                  "phone": "515.124.4269",
                  "salary": "$8,200.00",
                  "job": "Accountant",
                  "department": "Finance",
                  "manager": "Nancy Greenberg"
                },
                {
                  "employeeId": 111,
                  "firstName": "Ismael",
                  "lastName": "Sciarra",
                  "hireDate": "9/30/1997",
                  "email": "ismael.sciarra@sqltutorial.org",
                  "phone": "515.124.4369",
                  "salary": "$7,700.00",
                  "job": "Accountant",
                  "department": "Finance",
                  "manager": "Nancy Greenberg"
                },
                {
                  "employeeId": 112,
                  "firstName": "Jose Manuel",
                  "lastName": "Urman",
                  "hireDate": "3/7/1998",
                  "email": "jose manuel.urman@sqltutorial.org",
                  "phone": "515.124.4469",
                  "salary": "$7,800.00",
                  "job": "Accountant",
                  "department": "Finance",
                  "manager": "Nancy Greenberg"
                },
                {
                  "employeeId": 113,
                  "firstName": "Luis",
                  "lastName": "Popp",
                  "hireDate": "12/7/1999",
                  "email": "luis.popp@sqltutorial.org",
                  "phone": "515.124.4567",
                  "salary": "$6,900.00",
                  "job": "Accountant",
                  "department": "Finance",
                  "manager": "Nancy Greenberg"
                },
                {
                  "employeeId": 114,
                  "firstName": "Den",
                  "lastName": "Raphaely",
                  "hireDate": "12/7/1994",
                  "email": "den.raphaely@sqltutorial.org",
                  "phone": "515.127.4561",
                  "salary": "$11,000.00",
                  "job": "Purchasing Manager",
                  "department": "Purchasing",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 115,
                  "firstName": "Alexander",
                  "lastName": "Khoo",
                  "hireDate": "5/18/1995",
                  "email": "alexander.khoo@sqltutorial.org",
                  "phone": "515.127.4562",
                  "salary": "$3,100.00",
                  "job": "Purchasing Clerk",
                  "department": "Purchasing",
                  "manager": "Den Raphaely"
                },
                {
                  "employeeId": 116,
                  "firstName": "Shelli",
                  "lastName": "Baida",
                  "hireDate": "12/24/1997",
                  "email": "shelli.baida@sqltutorial.org",
                  "phone": "515.127.4563",
                  "salary": "$2,900.00",
                  "job": "Purchasing Clerk",
                  "department": "Purchasing",
                  "manager": "Den Raphaely"
                },
                {
                  "employeeId": 117,
                  "firstName": "Sigal",
                  "lastName": "Tobias",
                  "hireDate": "7/24/1997",
                  "email": "sigal.tobias@sqltutorial.org",
                  "phone": "515.127.4564",
                  "salary": "$2,800.00",
                  "job": "Purchasing Clerk",
                  "department": "Purchasing",
                  "manager": "Den Raphaely"
                },
                {
                  "employeeId": 118,
                  "firstName": "Guy",
                  "lastName": "Himuro",
                  "hireDate": "11/15/1998",
                  "email": "guy.himuro@sqltutorial.org",
                  "phone": "515.127.4565",
                  "salary": "$2,600.00",
                  "job": "Purchasing Clerk",
                  "department": "Purchasing",
                  "manager": "Den Raphaely"
                },
                {
                  "employeeId": 119,
                  "firstName": "Karen",
                  "lastName": "Colmenares",
                  "hireDate": "8/10/1999",
                  "email": "karen.colmenares@sqltutorial.org",
                  "phone": "515.127.4566",
                  "salary": "$2,500.00",
                  "job": "Purchasing Clerk",
                  "department": "Purchasing",
                  "manager": "Den Raphaely"
                },
                {
                  "employeeId": 120,
                  "firstName": "Matthew",
                  "lastName": "Weiss",
                  "hireDate": "7/18/1996",
                  "email": "matthew.weiss@sqltutorial.org",
                  "phone": "650.123.1234",
                  "salary": "$8,000.00",
                  "job": "Stock Manager",
                  "department": "Shipping",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 121,
                  "firstName": "Adam",
                  "lastName": "Fripp",
                  "hireDate": "4/10/1997",
                  "email": "adam.fripp@sqltutorial.org",
                  "phone": "650.123.2234",
                  "salary": "$8,200.00",
                  "job": "Stock Manager",
                  "department": "Shipping",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 122,
                  "firstName": "Payam",
                  "lastName": "Kaufling",
                  "hireDate": "5/1/1995",
                  "email": "payam.kaufling@sqltutorial.org",
                  "phone": "650.123.3234",
                  "salary": "$7,900.00",
                  "job": "Stock Manager",
                  "department": "Shipping",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 123,
                  "firstName": "Shanta",
                  "lastName": "Vollman",
                  "hireDate": "10/10/1997",
                  "email": "shanta.vollman@sqltutorial.org",
                  "phone": "650.123.4234",
                  "salary": "$6,500.00",
                  "job": "Stock Manager",
                  "department": "Shipping",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 126,
                  "firstName": "Irene",
                  "lastName": "Mikkilineni",
                  "hireDate": "9/28/1998",
                  "email": "irene.mikkilineni@sqltutorial.org",
                  "phone": "650.124.1224",
                  "salary": "$2,700.00",
                  "job": "Stock Clerk",
                  "department": "Shipping",
                  "manager": "Matthew Weiss"
                },
                {
                  "employeeId": 145,
                  "firstName": "John",
                  "lastName": "Russell",
                  "hireDate": "10/1/1996",
                  "email": "john.russell@sqltutorial.org",
                  "phone": null,
                  "salary": "$14,000.00",
                  "job": "Sales Manager",
                  "department": "Sales",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 146,
                  "firstName": "Karen",
                  "lastName": "Partners",
                  "hireDate": "1/5/1997",
                  "email": "karen.partners@sqltutorial.org",
                  "phone": null,
                  "salary": "$13,500.00",
                  "job": "Sales Manager",
                  "department": "Sales",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 176,
                  "firstName": "Jonathon",
                  "lastName": "Taylor",
                  "hireDate": "3/24/1998",
                  "email": "jonathon.taylor@sqltutorial.org",
                  "phone": null,
                  "salary": "$8,600.00",
                  "job": "Sales Representative",
                  "department": "Sales",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 177,
                  "firstName": "Jack",
                  "lastName": "Livingston",
                  "hireDate": "4/23/1998",
                  "email": "jack.livingston@sqltutorial.org",
                  "phone": null,
                  "salary": "$8,400.00",
                  "job": "Sales Representative",
                  "department": "Sales",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 178,
                  "firstName": "Kimberely",
                  "lastName": "Grant",
                  "hireDate": "5/24/1999",
                  "email": "kimberely.grant@sqltutorial.org",
                  "phone": null,
                  "salary": "$7,000.00",
                  "job": "Sales Representative",
                  "department": "Sales",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 179,
                  "firstName": "Charles",
                  "lastName": "Johnson",
                  "hireDate": "1/4/2000",
                  "email": "charles.johnson@sqltutorial.org",
                  "phone": null,
                  "salary": "$6,200.00",
                  "job": "Sales Representative",
                  "department": "Sales",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 192,
                  "firstName": "Sarah",
                  "lastName": "Bell",
                  "hireDate": "2/4/1996",
                  "email": "sarah.bell@sqltutorial.org",
                  "phone": "650.501.1876",
                  "salary": "$4,000.00",
                  "job": "Shipping Clerk",
                  "department": "Shipping",
                  "manager": "Shanta Vollman"
                },
                {
                  "employeeId": 193,
                  "firstName": "Britney",
                  "lastName": "Everett",
                  "hireDate": "3/3/1997",
                  "email": "britney.everett@sqltutorial.org",
                  "phone": "650.501.2876",
                  "salary": "$3,900.00",
                  "job": "Shipping Clerk",
                  "department": "Shipping",
                  "manager": "Shanta Vollman"
                },
                {
                  "employeeId": 200,
                  "firstName": "Jennifer",
                  "lastName": "Whalen",
                  "hireDate": "9/17/1987",
                  "email": "jennifer.whalen@sqltutorial.org",
                  "phone": "515.123.4444",
                  "salary": "$4,400.00",
                  "job": "Administration Assistant",
                  "department": "Administration",
                  "manager": "Neena Kochhar"
                },
                {
                  "employeeId": 201,
                  "firstName": "Michael",
                  "lastName": "Hartstein",
                  "hireDate": "2/17/1996",
                  "email": "michael.hartstein@sqltutorial.org",
                  "phone": "515.123.5555",
                  "salary": "$13,000.00",
                  "job": "Marketing Manager",
                  "department": "Marketing",
                  "manager": "Steven King"
                },
                {
                  "employeeId": 202,
                  "firstName": "Pat",
                  "lastName": "Fay",
                  "hireDate": "8/17/1997",
                  "email": "pat.fay@sqltutorial.org",
                  "phone": "603.123.6666",
                  "salary": "$6,000.00",
                  "job": "Marketing Representative",
                  "department": "Marketing",
                  "manager": "Michael Hartstein"
                },
                {
                  "employeeId": 203,
                  "firstName": "Susan",
                  "lastName": "Mavris",
                  "hireDate": "6/7/1994",
                  "email": "susan.mavris@sqltutorial.org",
                  "phone": "515.123.7777",
                  "salary": "$6,500.00",
                  "job": "Human Resources Representative",
                  "department": "Human Resources",
                  "manager": "Neena Kochhar"
                },
                {
                  "employeeId": 204,
                  "firstName": "Hermann",
                  "lastName": "Baer",
                  "hireDate": "6/7/1994",
                  "email": "hermann.baer@sqltutorial.org",
                  "phone": "515.123.8888",
                  "salary": "$10,000.00",
                  "job": "Public Relations Representative",
                  "department": "Public Relations",
                  "manager": "Neena Kochhar"
                },
                {
                  "employeeId": 205,
                  "firstName": "Shelley",
                  "lastName": "Higgins",
                  "hireDate": "6/7/1994",
                  "email": "shelley.higgins@sqltutorial.org",
                  "phone": "515.123.8080",
                  "salary": "$12,000.00",
                  "job": "Accounting Manager",
                  "department": "Accounting",
                  "manager": "Neena Kochhar"
                },
                {
                  "employeeId": 206,
                  "firstName": "William",
                  "lastName": "Gietz",
                  "hireDate": "6/7/1994",
                  "email": "william.gietz@sqltutorial.org",
                  "phone": "515.123.8181",
                  "salary": "$8,300.00",
                  "job": "Public Accountant",
                  "department": "Accounting",
                  "manager": "Shelley Higgins"
                }
              ]
        ],
        applicants:[]
    }
    return data;
}